[manager]
ratio = [1, 4, 5] # default [1, 4, 3]，3 列。
show_hidden = true
linemode = "size_and_mtime"
show_symlink = true
mouse_events = ["click", "scroll", "touch"]
scrolloff = 5

[[plugin]]
previewers = [
  { name = "*/", run = "folder", sync = true },
  # { name = "*.md", run = "preview" },
  # { name = "*.csv", run = "preview" },
  { mime = "text/*", run = "code" },
  { mime = "*/xml", run = "code" },
  { mime = "*/javascript", run = "code" },
  { mime = "*/x-wine-extension-ini", run = "code" },
  { name = "*", run = "preview" },
]

prepend_previewers = [
    { name = "*.csv", exec = "bat" },
    { name = "*.md", exec = "bat" }
]
